## Numpy
### 001 ~ 010

In [1]:
# 1. 넘파이 임포트
import numpy as np

In [2]:
# 2. ndarray
data = [1, 2, 3]
np.array(data)

array([1, 2, 3])

In [ ]:
# 3. arange
np.arange(100)

In [ ]:
# 4. arange
np.arange(1,10)*3

In [ ]:
# 5. arange
np.arange(2,1000,2)

In [3]:
# 6. 실수 range
np.arange(0,1,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [4]:
# 7. reshape
data = [0,1,2,3,4,5]
arr = np.array(data)
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
# 8. reshape
